version: appveyor.{build}
clone_folder: c:\dev\wb-toolbox
clone_depth: 1

platform: x64
configuration: Release

image:
  - Visual Studio 2015
  - Visual Studio 2017

skip_tags: true
skip_branch_with_pr: true

build:
  parallel: true
  verbosity: detailed

matrix:
  fast_finish: true

pull_requests:
  do_not_increment_build_number: true

init:
  - ps: $YARP_LATEST = "2.3.72"
  - ps: $ICUB_LATEST = "1.10.0"
  - ps: $ROBOTOLOGY_VS = "v14"
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2015') { $GENERATOR = "Visual Studio 14 2015 Win64" }
  - ps: if ($env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2017') { $GENERATOR = "Visual Studio 15 2017 Win64" }

install:
  - ps: Start-FileDownload https://github.com/robotology/yarp/releases/download/v${YARP_LATEST}/yarp_${YARP_LATEST}_${ROBOTOLOGY_VS}_x86_amd64_1.exe -FileName c:\dev\yarp.exe -Timeout 300000
  - ps: Start-FileDownload https://github.com/robotology/icub-main/releases/download/v${ICUB_LATEST}/iCub_${ICUB_LATEST}_${ROBOTOLOGY_VS}_x86_amd64_1.exe -FileName c:\dev\icub.exe -Timeout 300000
  - ps: Start-Process -FilePath "c:\dev\yarp.exe" -ArgumentList "/S" -Wait -NoNewWindow -PassThru
  - ps: Start-Process -FilePath "c:\dev\icub.exe" -ArgumentList "/S" -Wait -NoNewWindow -PassThru

  - ps: |
      # From: https://www.michaelmiklis.de/update-environment-variables-in-current-process/
      # Modified to append appveyor's path
      $ENV_MACHINE = ([Environment]::GetEnvironmentVariables('Machine'))
      foreach ($EnvVar in $ENV_MACHINE.keys) {
        Set-Item "Env:$($EnvVar)" -Value $ENV_MACHINE[$EnvVar]
      }
      $ENV_USER = ([Environment]::GetEnvironmentVariables('User'))
      foreach ($EnvVar in $ENV_USER.keys) {
        if ($EnvVar -ne 'Path') {
          Set-Item "Env:$($EnvVar)" -Value $ENV_USER[$EnvVar]
        }
      }
      if ($ENV_USER.ContainsKey('Path')) {
        Set-Item Env:Path -Value ((($env:Path -split ";") + ($ENV_USER.Path -split ";") + ($ENV_MACHINE.Path -split ";") | select -Unique) -join ";")
      }

  - ps: git clone -q --depth 1 https://github.com/robotology/idyntree.git c:\dev\idyntree
  - ps: cd c:\dev\idyntree
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G"$GENERATOR" -DIDYNTREE_USES_QT5:BOOL=OFF ..
  - ps: cmake --build . --config $env:CONFIGURATION --target INSTALL

  - ps: git clone -q --depth 1 https://github.com/robotology/ycm.git c:\dev\ycm
  - ps: mkdir "c:\Program Files\robotology\ycm"
  - ps: $env:YCM_DIR = "C:/Program Files/robotology/ycm/share/YCM/cmake/"
  - ps: cd c:\dev\ycm
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -Wno-dev -G"$GENERATOR" -DCMAKE_INSTALL_PREFIX:PATH="c:\Program Files\robotology\ycm" ..
  - ps: cmake --build . --config $env:CONFIGURATION --target INSTALL

build_script:
  - ps: cd $env:APPVEYOR_BUILD_FOLDER
  - ps: mkdir build
  - ps: cd build
  - ps: cmake -G"$GENERATOR" ..
  - ps: cmake --build . --config $env:CONFIGURATION
