site_name: 'WB-Toolbox'
site_description: 'A Simulink Toolbox for Whole Body Control'
site_author: 'Diego Ferigo'
theme: 'material'
repo_url: 'https://github.com/robotology/WB-Toolbox'
edit_uri: 'edit/master/docs/mkdocs/data'
docs_dir: 'data'
pages:
- Home: 'index.md'
- Install: 'install.md'
- Getting started: 'getting-started.md'
- Troubleshooting: 'troubleshooting.md'
- Developer area:
    - Add a new block: 'create_new_block.md'
    - Simulink Tricks: 'sim_tricks.md'
- Migration:
    - From WBI-Toolbox: 'Migration_from_WBI-Toolbox_1.0.md'
    - From WB-Toolbox 2.0: 'Migration_from_WB-Toolbox_2.0.md'
- About: 'about.md'
