name: CI

on:
  push:
  pull_request:

jobs:

  ci:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:

      - uses: actions/checkout@master
      - run: git fetch --prune --unshallow

      - name: 'Ubuntu: System Dependencies'
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libace-dev libeigen3-dev libgsl-dev libedit-dev \
            python3-numpy libxml2-dev coinor-libipopt-dev \
            ninja-build

      - name: 'MacOS: System Dependencies'
        if: matrix.os == 'macos-latest'
        run: brew install ace assimp eigen tinyxml gsl ipopt ninja

      - name: Setup dependencies branch [master]
        if: |
          github.ref == 'refs/heads/master' ||
          (github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'refs/heads/master')
        run: echo "DEPS_BRANCH=master" >> $GITHUB_ENV

      - name: Setup dependencies branch [other]
        if: |
          (github.event_name == 'push' && github.ref != 'refs/heads/master') ||
          (github.event_name == 'pull_request' && github.event.pull_request.head.ref != 'refs/heads/master')
        run: echo "DEPS_BRANCH=devel" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          export DEPS_CACHE=$HOME/deps
          export PATH=$PATH:$DEPS_CACHE/bin
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$DEPS_CACHE
          ./.ci/install.sh || false
        env:
          CMAKE_GENERATOR: Ninja
          CMAKE_BUILD_TYPE: Debug

      - name: Build
        run: |
          export DEPS_CACHE=$HOME/deps
          export PATH=$PATH:$DEPS_CACHE/bin
          export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:$DEPS_CACHE
          mkdir build && cd build
          cmake ..\
            -G"$CMAKE_GENERATOR" \
            -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
          cmake --build . --config $CMAKE_BUILD_TYPE
        env:
          CMAKE_GENERATOR: Ninja
          CMAKE_BUILD_TYPE: Debug
